### ISSUE TITLE
Rename event thing

### ISSUE THREAD

**Issue by DragonDev15** [reloadedjs/reloaded#1]
In the `client.connect` feature the "connect" part I do not think fits the best maybe something like `client.load`. Try to be unique!

**Comment by NotMarx** [comment]
> In the `client.connect` feature the "connect" part I do not think fits the best maybe something like `client.load`. Try to be unique!

Well, technically in sense, it should be `connect` as it was represent to connecting the client to the Discord Gateway. `load` just doesn't seems to making any sense in my opinion.

**Comment by DragonDev15** [comment]
> Well, technically in sense, it should be `connect` as it was represent to connecting the client to the Discord Gateway. `load` just doesn't seems to making any sense in my opinion.

Good point. You could do client.reload to show its "reloading" 😜

**Comment by NotMarx** [comment]
> Good point. You could do client.reload to show its "reloading" 😜

I'll see what I can do with this. But for now, it'll be `connect()` until we, the team discuss this further.

**Comment by Veilorth** [comment]
> In the `client.connect` feature the "connect" part I do not think fits the best maybe something like `client.load`. Try to be unique!

We won't be changing `client.connect()` to anything else for now. We prefer this way to stays forever (might change in the future if possible).
